name: Sync to Bitbucket

on:
  push:
    branches:
      - main
      - master
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Bitbucket
        run: |
          git remote add bitbucket https://$BITBUCKET_USER:$BITBUCKET_TOKEN@bitbucket.org/retynai/aziend-live-infra.git
          git push bitbucket --all
          git push bitbucket --tags
